all:
	mkdir -p ../img
	rm ../img/*
	cp -vu img/*png ../img/
	cp -vu img/*svg ../img/
	mkdir -p ../fonts
	rm -rf ../fonts/*
	cp -R fonts ..
	cp onerng.css ..
	cp diceimg.js ..
	cp README.md ..
	cp CNAME ..
	ttree -f ttreerc

