#!/bin/bash

for i in pic/*png pic/*jpg
do
    img=$(file $i | cut -d: -f2)
    size=$(ls -lh $i | cut -d' ' -f5)
    t=${i/.png/.tt2}
    t=${t/.jpg/.tt2}

    cat >$t <<EOF
[% PROCESS header %]

<h3>Image Assets</h3>
<h4>$(basename $i)</h4>
<p>$size $img</p>

<hr/>
<div class="imgbar">
<img src="/$i"/>
</div>

[% INCLUDE footer %]
EOF
done

